-- Initial migration for Ceres Network backend
-- This is a placeholder - run `npx drizzle-kit generate:pg` to generate actual migrations

-- Example structure (actual migrations will be generated by Drizzle Kit):

-- CREATE TABLE policies (
--   policy_id BIGINT PRIMARY KEY,
--   farmer VARCHAR(56) NOT NULL,
--   farm_geohash VARCHAR(12) NOT NULL,
--   crop_type VARCHAR(64) NOT NULL,
--   season_start TIMESTAMP NOT NULL,
--   season_end TIMESTAMP NOT NULL,
--   coverage_amount BIGINT NOT NULL,
--   rainfall_threshold BIGINT NOT NULL,
--   ndvi_baseline BIGINT NOT NULL,
--   status VARCHAR(16) NOT NULL DEFAULT 'active',
--   registered_ledger BIGINT NOT NULL,
--   registered_at TIMESTAMP NOT NULL,
--   updated_at TIMESTAMP NOT NULL
-- );

-- CREATE INDEX policies_farmer_idx ON policies(farmer);
-- CREATE INDEX policies_geohash_idx ON policies(farm_geohash);
-- CREATE INDEX policies_status_idx ON policies(status);

-- ... (other tables)

-- To generate actual migrations, run:
-- npx drizzle-kit generate:pg --schema=./packages/shared/src/schema.ts --out=./db/migrations
